package com.example.capstone2test.roomDatabase.data

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.parcelize.Parcelize

@Parcelize
@Entity(tableName = "reading_table") // Reading Entity represents a table within the database.
data class Reading(
    @PrimaryKey(autoGenerate = true)
    val id: Int, // <- 'id' is the primary key which will be autogenerated by the Room library.
    val diseaseName: String,
    var sysName: String,
    var date: String,
    var aioName: Int =0
): Parcelable